version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus-monitoring.yml
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: emigiusto/grafana
    ports:
      - 3005:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin