version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:
  minitwitimage:
    build:
      context: .
      dockerfile: itu-minitwit-node/Dockerfile
    image: emigiusto/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
        - '5000:5000'
    depends_on:
      - grafana
      - prometheus

  flagtool:
    build:
      context: .
      dockerfile: flag_tool/Dockerfile
    image: emigiusto/flag-tool
    container_name: flag-tool
    networks:
      - main
    command: tail -f /dev/null

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: emigiusto/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin