version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - main
    volumes:
      - ./prometheus-monitoring.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: emigiusto/grafana
    ports:
      - 3005:3000
    networks:
      - main
    depends_on:
      - prometheus