version: '3.3'

networks:
  elk:

volumes:
    elk_elasticsearch_data:

services:
  minitwitimage:
    build:
      context: .
      dockerfile: itu-minitwit-node/Dockerfile
    image: minitwitimage
    container_name: minitwit
    networks:
      elk
    ports:
      '5000:5000'
    volumes:
      elk_elasticsearch_data:/app/logs
      #/app/logs:/app/logs
    deploy: 
      replicas: 3
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==manager"
      

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.1"
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
    volumes:
        elk_elasticsearch_data:/var/lib/elasticsearch/data
    networks:
        elk
    deploy: 
      endpoint_mode: vip
      placement:
        constraints:
          "node.role==worker"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.1"
    container_name: kibana
    environment:
        elasticsearch.hosts: '["http://elasticsearch:9200"]'
    ports:
      "5601:5601"
    networks:
      elk
    deploy: 
      endpoint_mode: vip
      placement:
        constraints:
          "node.role==worker"

  filebeat:
    build:
      context: .
      dockerfile: filebeat/Dockerfile
    image: filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    environment:
      user: root
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - elk_elasticsearch_data:/app/logs
      #- /app/logs:/app/logs
    networks:
      elk
    depends_on:
      elasticsearch
    deploy: 
      endpoint_mode: vip
      placement:
        constraints:
          "node.role==manager"

  flagtool:
    build:
      context: .
      dockerfile: flag_tool/Dockerfile
    image: flag-tool
    container_name: flag-tool
    command: tail -f /dev/null
    deploy: 
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==worker"
          - "node.label==logging"
