{
 "title": "Minitwit Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_health{app=\"minitwit-app\"}"
    }
   ]
  },
  {
   "title": "Minitwit status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{app=\"minitwit-app\"}"
    }
   ]
  },
  {
   "title": "HTTP Errors total Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_error_requests_total{app=\"minitwit-app\"})"
    }
   ]
  },
  {
   "title": "Hours running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - minitwit_node_process_start_time_seconds)  / 3600"
    }
   ]
  },
  {
   "title": "HTTP Errors total Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, code) (http_error_codes{app=\"minitwit-app\"})"
    }
   ]
  },
  {
   "title": "Minitwit active requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "minitwit_node_nodejs_active_requests{type=\"FSReqCallback\"}"
    }
   ]
  },
  {
   "title": "Minitwit virtual memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minitwit_node_process_virtual_memory_bytes{app=\"minitwit-app\"}"
    }
   ]
  },
  {
   "title": "Minitwit heap size used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minitwit_node_nodejs_heap_size_used_bytes"
    }
   ]
  },
  {
   "title": "Histograms of Response time per Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "POST /msgs/ Response time in millisecs",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"minitwit-app\",method=\"POST\",route=\"/msgs/\"}"
    }
   ]
  },
  {
   "title": "GET /msgs/ Response time in millisecs",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"minitwit-app\",method=\"GET\",route=\"/msgs/\"}"
    }
   ]
  },
  {
   "title": "POST /fllws/ Response time in millisecs",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"minitwit-app\",method=\"POST\",route=\"/fllws/\"}"
    }
   ]
  },
  {
   "title": "GET /fllws/ Response time in millisecs",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"minitwit-app\",method=\"GET\",route=\"/fllws/\"}"
    }
   ]
  },
  {
   "title": "POST /register/ Response time in millisecs",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"minitwit-app\",method=\"POST\",route=\"/register/\"}"
    }
   ]
  },
  {
   "title": "GET /latest/ Response time in millisecs",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"minitwit-app\",method=\"GET\",route=\"/latest/\"}"
    }
   ]
  }
 ]
}