apiVersion: 1
dataSources:
  - name: Prometheus
    type: prometheus
    access: direct
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: GET
      tlsSkipVerify: true