version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
        - '5000:5000'
    #If we self host the mysql database, we need to uncomment this
    #depends_on:
    #  - mysqlminitwit

  flagtool:
    image: ${DOCKER_USERNAME}/flag-tool
    container_name: flag-tool
    networks:
      - main
    command: tail -f /dev/null
    #If we self host the mysql database, we need to uncomment this
    #depends_on:
    #  - mysqlminitwit

  # Elasticsearch
  eslogs:
    image: elasticsearch:7.8.0
    container_name: eslogs
    volumes:
      - ../elastic/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  
  kibana_demo:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana_demo
    volumes:
    - ../elastic/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  logstash_demo:
    image: logstash:7.8.1
    container_name: logstash_demo
    volumes:
    - ../elastic/logging.conf:/usr/share/logstash/pipeline/logging.conf
    - ../elastic/logstash.yaml:/usr/share/logstash/config/logstash.yml
    ports:
    - 1514:1514/udp
    - 1515:1515
    - 1515:1515/udp
  
