version: '3.3'

networks:
  main:

volumes:
  elk_elasticsearch_data:

services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
      - '3000:3000'
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - elk_elasticsearch_data:/app/logs

  flagtool:
    image: ${DOCKER_USERNAME}/flag-tool
    container_name: flag-tool
    networks:
      - main
    command: tail -f /dev/null
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
  filebeat:
    image: ${DOCKER_USERNAME}/filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    environment:
      user: root
    volumes:
      - ./filebeat/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - elk_elasticsearch_data:/app/logs