---
name: Continuous Integration

on:
  pull_request: {}
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          cd itu-minitwit-node
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: 
          cd itu-minitwit-node
          npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif

      #- name: ESLint
      #  
      #  run: |
      #    cd itu-minitwit-node/
      #    npm install
      #    npm run lint

      - name: Giving permissions to logger files
        run: |
          sudo mkdir -p /var/log/minitwit
          sudo touch /var/log/minitwit/errors.log
          sudo touch /var/log/minitwit/combined.log
          sudo chmod a+rwx /var/log/minitwit/errors.log
          sudo chmod a+rwx /var/log/minitwit/combined.log

      - name: Cypress testing 
        uses: cypress-io/github-action@v5
        with: 
          working-directory: itu-minitwit-node
          start: npm start
          config-file: cypress.config.js
          wait-on: "http://localhost:3000/api"
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

      - name: Test minitwit
        run: |
          docker build -t minitwit-tests -f ./itu-minitwit-node/tests/Dockerfile .
          docker run --rm -e MYSQL_PASSWORD=$MYSQL_PASSWORD   -e MYSQL_USERNAME=$MYSQL_USERNAME   -e MYSQL_HOST=$MYSQL_HOST   -e MYSQL_PORT=$MYSQL_PORT   -e MYSQL_DATABASE=$MYSQL_DATABASE minitwit-tests
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

      


          
